language: python
python:
  - "2.7"
  - "3.3"

install:
  # Install and configure Miniconda
  - sudo apt-get update
  - sudo apt-get install zsh
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.0.0-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda info -a

  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pip statsmodels
  - source activate test-environment

  # Install non-critical dependencies via pip
  - pip install -r requirements.txt
  - pip install -e .
  - python setup.py install

script:
  - py.test
